name: Build document

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  dependencies:
    name: Build dependencies
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Create global variables
        id: version
        run: echo "version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build_latex:
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          # root_file: "*.tex"
          # glob_root_file: true
          root_file: "history.tex"
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: history
          path: |
            *.pdf

      - name: Release (${{ needs.dependencies.outputs.version }})
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}-${{ needs.dependencies.outputs.version }}
          name: Version ${{ github.run_number }} (${{ needs.dependencies.outputs.version }})
          prerelease: true
          files: history.pdf
